const typesofcats=[
  "American Shorthair",
  "British Shorthair",
  "Siamese Cats",
  "Persian Cats",
  "Ragdoll Cats",
  "Maine Coon",
  "Sphynx Cat",
  "Burmese Cats",
  "Russian Blue Cats",
  "Exotic Shorthair",
  "Scottish Fold",
  "Bengal Cats",
  "Abyssinian Cats",
  "Devon Rex Cats",
  "Himalayan Cats",
  "Japanese Bobtail Cats",
  "Norwegian Forest Cats",
  "Ocicat Cats",
  "Savannah Cats",
  "Siberian Cats",
  "Turkish Angora Cats",
  "Turkish Van Cats",
  "Chartreux Cats",
  "Havana Brown Cats",
  "LaPerm Cats",
  "Manx Cats",
  "Munchkin Cats",
  "Peterbald Cats",
  "Ragamuffin Cats",
  "Siberian Cats",
  "Snowshoe Cats",
  "Toyger Cats",
  "Turkish Van Cats",
  "Turkish Angora Cats",
  "American Curl Cats",
  "Balinese Cats",
  "Birman Cats",
  "Bombay Cats",
  "British Longhair Cats",
  "Burmilla Cats",
  "Chartreux Cats",
  "Devon Rex Cats",
  "Egyptian Mau Cats",
  "Exotic Shorthair Cats",
  "Havana Brown Cats",
  "Himalayan Cats",
]

function generateAnimal() {
  const randomIndex = Math.floor(Math.random()*typesofcats.length);
  const randomCat = typesofcats[randomIndex];
  document.getElementById("animalDisplay").innerHTML = randomCat;
}
